---
language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
jobs:
  allow_failures:
  - rvm: ruby-head
before_install: gem install bundler -v 2.1.4
install:
  - bundle install
before_script:
  - bundle exec rake clean clobber
script:
  - sudo env RBENV_VERSION="${RBENV_VERSION}" PATH="${RBENV_ROOT}/shims:${RBENV_ROOT}/bin:${PATH}" bundle exec rake compile spec
after_script:
  - bundle exec rake clean clobber
